#-----------------------------------------------
# config.system.yaml user setting
# 
# config.system.default.yamlの値をこのファイルで
# 上書きすることが出来ます。
#-----------------------------------------------

### 例 jQueryのバージョンを切り替える
#jquery_version : 1.8.3 # (1.8.3|1.7.2|1.6.4)